CREATE TABLE Account (Account text NOT NULL PRIMARY KEY UNIQUE, Password text NOT NULL);
CREATE TABLE Category (Category_ID INTEGER PRIMARY KEY AUTOINCREMENT, Account TEXT REFERENCES Account (Account) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, Category TEXT NOT NULL);
CREATE TABLE SubCategory (SubCategory_ID INTEGER PRIMARY KEY AUTOINCREMENT, Account TEXT REFERENCES Account (Account) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, Category_ID INTEGER REFERENCES Category (Category_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, SubCategory TEXT NOT NULL);
CREATE TABLE Record (Record_ID INTEGER PRIMARY KEY AUTOINCREMENT, Account TEXT REFERENCES Account (Account) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, Category_ID INTEGER REFERENCES Category (Category_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, SubCategory_ID INTEGER REFERENCES SubCategory (SubCategory_ID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, Login TEXT, Password text, ElseData text);

DROP TABLE Record;
DROP TABLE SubCategory;
DROP TABLE Category;
DROP TABLE Account;


